//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilentAuction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilentAuction.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update the latest bids. Contact the auction manager..
        /// </summary>
        public static string AuctionCannotGetBids {
            get {
                return ResourceManager.GetString("AuctionCannotGetBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh this page or wait a few moments to see the final results..
        /// </summary>
        public static string AuctionStatusClosedDetail {
            get {
                return ResourceManager.GetString("AuctionStatusClosedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction has closed.
        /// </summary>
        public static string AuctionStatusClosedTitle {
            get {
                return ResourceManager.GetString("AuctionStatusClosedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the auction to be resumed..
        /// </summary>
        public static string AuctionStatusPausedDetail {
            get {
                return ResourceManager.GetString("AuctionStatusPausedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction is paused.
        /// </summary>
        public static string AuctionStatusPausedTitle {
            get {
                return ResourceManager.GetString("AuctionStatusPausedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the auction to start..
        /// </summary>
        public static string AuctionStatusPendingDetail {
            get {
                return ResourceManager.GetString("AuctionStatusPendingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This auction has not started..
        /// </summary>
        public static string AuctionStatusPendingTitle {
            get {
                return ResourceManager.GetString("AuctionStatusPendingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The auction is unavailable..
        /// </summary>
        public static string AuctionUnavailable {
            get {
                return ResourceManager.GetString("AuctionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many decimal places..
        /// </summary>
        public static string DecimalPlacesInvalid {
            get {
                return ResourceManager.GetString("DecimalPlacesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0}..
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors were found:.
        /// </summary>
        public static string ErrorsFollowingFound {
            get {
                return ResourceManager.GetString("ErrorsFollowingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filesize is a maximum of {0} MB..
        /// </summary>
        public static string FileTooBig {
            get {
                return ResourceManager.GetString("FileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For individual image files, reduce the file size in a photo editor. 
        ///
        ///If uploading several image files and you do not wish to reduce the image size, try uploading fewer; you can add more by editing this item later. But each file must be below the maximum upload size.
        ///
        ///The maximum upload size is specified in the application configuration. .
        /// </summary>
        public static string ImagesTooBigGeneralHelp {
            get {
                return ResourceManager.GetString("ImagesTooBigGeneralHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank entry for {0}.
        /// </summary>
        public static string ImportFieldCannotBeBlank {
            get {
                return ResourceManager.GetString("ImportFieldCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; contains no data.
        /// </summary>
        public static string ImportFileEmpty {
            get {
                return ResourceManager.GetString("ImportFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No headers found.
        /// </summary>
        public static string ImportFileNoHeader {
            get {
                return ResourceManager.GetString("ImportFileNoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import files are too big. If importing several files, import fewer at a time.
        ///
        ///If importing a very large file, split the data over more than one file and upload them seperately..
        /// </summary>
        public static string ImportFilesTooBigGeneralHelp {
            get {
                return ResourceManager.GetString("ImportFilesTooBigGeneralHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contain the required header &quot;{0}&quot;.
        /// </summary>
        public static string ImportHeaderMissing {
            get {
                return ResourceManager.GetString("ImportHeaderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} columns but found {1}.
        /// </summary>
        public static string ImportLineWrongNoOfCols {
            get {
                return ResourceManager.GetString("ImportLineWrongNoOfCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data was imported..
        /// </summary>
        public static string ImportNoDataImported {
            get {
                return ResourceManager.GetString("ImportNoDataImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot {0} is already locked by user &quot;{1}&quot;..
        /// </summary>
        public static string LotLocked {
            get {
                return ResourceManager.GetString("LotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get a lock on lot {0} for user &quot;{1}&quot;..
        /// </summary>
        public static string LotLockFailed {
            get {
                return ResourceManager.GetString("LotLockFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock on lot {0} has been taken unexpectedly..
        /// </summary>
        public static string LotLockStolen {
            get {
                return ResourceManager.GetString("LotLockStolen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not release lock on lot {0} for user &quot;{1}&quot;..
        /// </summary>
        public static string LotUnlockFailed {
            get {
                return ResourceManager.GetString("LotUnlockFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please notify the Auction Manager..
        /// </summary>
        public static string PleaseNotifyAuctionManager {
            get {
                return ResourceManager.GetString("PleaseNotifyAuctionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This system does not allow users to register. Please ask the Auction manager for a login..
        /// </summary>
        public static string RegistrationNotManual {
            get {
                return ResourceManager.GetString("RegistrationNotManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reserve must be a positive number.
        /// </summary>
        public static string ReserveMustBePositiveNumber {
            get {
                return ResourceManager.GetString("ReserveMustBePositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned an unexpected error..
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only select {0} file(s)..
        /// </summary>
        public static string TooManyFiles {
            get {
                return ResourceManager.GetString("TooManyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total size of files cannot be bigger than {0} MB. .
        /// </summary>
        public static string TotalUploadTooBig {
            get {
                return ResourceManager.GetString("TotalUploadTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
