//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilentAuction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilentAuction.Resources.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create CSV files with lot details and import them here.
        ///
        ///CSV files can be exported from a spreadsheet (see your speadsheet documentation for how to do this).
        ///
        ///The required fields are: Name, Description, Reserve.
        /// </summary>
        public static string ImportHelp {
            get {
                return ResourceManager.GetString("ImportHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting for the maximum size of file uploads is found in the application configuration files. See the web.config file, under:
        ///
        ///    &lt;system.web&gt;
        ///        &lt;httpRuntime maxRequestLength=&quot;{max upload size KB}&quot;&gt;
        ///
        ///Change the setting on the web server and restart the application to allow larger amounts of data to be uploaded. Note that the actual maximum used is slightly less, because the form data must also be passed in the request to the server.
        ///
        ///Note also that the web server must be configured to allo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MaxUploadSize {
            get {
                return ResourceManager.GetString("MaxUploadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more details.
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
    }
}
