//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilentAuction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParameterDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParameterDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilentAuction.Resources.ParameterDetails", typeof(ParameterDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow an email address to be entered by users. The email address is optional unless the parameter &quot;Force Email&quot; is set..
        /// </summary>
        public static string AllowEmailDescription {
            get {
                return ResourceManager.GetString("AllowEmailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Email.
        /// </summary>
        public static string AllowEmailName {
            get {
                return ResourceManager.GetString("AllowEmailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow users to register on the site. If this option is disabled, then an administrator will have to create user accounts manually, and assign them to auctions. See also: &quot;Users allowed in any auction&quot;..
        /// </summary>
        public static string AllowRegistrationDescription {
            get {
                return ResourceManager.GetString("AllowRegistrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow registration.
        /// </summary>
        public static string AllowRegistrationName {
            get {
                return ResourceManager.GetString("AllowRegistrationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string BooleanNo {
            get {
                return ResourceManager.GetString("BooleanNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string BooleanYes {
            get {
                return ResourceManager.GetString("BooleanYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned on, a space will be inserted between the currency cymbol and the value. eg &quot;5,000CAD&quot; has no space, but &quot;5,000 CAD&quot; has a space..
        /// </summary>
        public static string CurrencyAddSpaceDescription {
            get {
                return ResourceManager.GetString("CurrencyAddSpaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add space between numbers and currency symbol.
        /// </summary>
        public static string CurrencyAddSpaceName {
            get {
                return ResourceManager.GetString("CurrencyAddSpaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not to show decimal places with the currency. If turned on, then two decimal places are shown..
        /// </summary>
        public static string CurrencyDecimalPlacesDescription {
            get {
                return ResourceManager.GetString("CurrencyDecimalPlacesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency decimal places.
        /// </summary>
        public static string CurrencyDecimalPlacesName {
            get {
                return ResourceManager.GetString("CurrencyDecimalPlacesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to display the currency symbol as part of a value (eg &quot;£50,000&quot; is positioned to the left, whereas &quot;5,000 CAD&quot; is positioned to the right.
        /// </summary>
        public static string CurrencyPositionDescription {
            get {
                return ResourceManager.GetString("CurrencyPositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency symbol position.
        /// </summary>
        public static string CurrencyPositionName {
            get {
                return ResourceManager.GetString("CurrencyPositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol or text to display as the currency part of a value. For example: $, £, CAD$.
        /// </summary>
        public static string CurrencyTextDescription {
            get {
                return ResourceManager.GetString("CurrencyTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency symbol or text.
        /// </summary>
        public static string CurrencyTextName {
            get {
                return ResourceManager.GetString("CurrencyTextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, any user can enter any currently-running auction. After the auction ends, they will be allowed to bid on items in later auctions using the same account details.
        ///
        ///If disabled, then an administrator must assign users to auctions manually..
        /// </summary>
        public static string UsersAllowedAnyAuctionDescription {
            get {
                return ResourceManager.GetString("UsersAllowedAnyAuctionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users allowed in any auction.
        /// </summary>
        public static string UsersAllowedAnyAuctionName {
            get {
                return ResourceManager.GetString("UsersAllowedAnyAuctionName", resourceCulture);
            }
        }
    }
}
