//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilentAuction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilentAuction.Resources.TextStrings", typeof(TextStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Tools.
        /// </summary>
        public static string AdministratorTools {
            get {
                return ResourceManager.GetString("AdministratorTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin setting.
        /// </summary>
        public static string AdminSetting {
            get {
                return ResourceManager.GetString("AdminSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Auction &quot;{0}&quot;.
        /// </summary>
        public static string AuctionClose {
            get {
                return ResourceManager.GetString("AuctionClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the auction. All bidding is stopped. Users can see the highest bidders. Use &quot;pause&quot; to temporarily stop bidding..
        /// </summary>
        public static string AuctionCloseHelp {
            get {
                return ResourceManager.GetString("AuctionCloseHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string AuctionCloseLink {
            get {
                return ResourceManager.GetString("AuctionCloseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction Configuration.
        /// </summary>
        public static string AuctionConfiguration {
            get {
                return ResourceManager.GetString("AuctionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Auction.
        /// </summary>
        public static string AuctionCreate {
            get {
                return ResourceManager.GetString("AuctionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AuctionDescription {
            get {
                return ResourceManager.GetString("AuctionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Auction.
        /// </summary>
        public static string AuctionEdit {
            get {
                return ResourceManager.GetString("AuctionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction Image.
        /// </summary>
        public static string AuctionImage {
            get {
                return ResourceManager.GetString("AuctionImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AuctionName {
            get {
                return ResourceManager.GetString("AuctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction is not open..
        /// </summary>
        public static string AuctionNotRunning {
            get {
                return ResourceManager.GetString("AuctionNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause auction &quot;{0}&quot;.
        /// </summary>
        public static string AuctionPause {
            get {
                return ResourceManager.GetString("AuctionPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporarily prevents bidding until restarted..
        /// </summary>
        public static string AuctionPauseHelp {
            get {
                return ResourceManager.GetString("AuctionPauseHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string AuctionPauseLink {
            get {
                return ResourceManager.GetString("AuctionPauseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen auction &quot;{0}&quot;.
        /// </summary>
        public static string AuctionReopen {
            get {
                return ResourceManager.GetString("AuctionReopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopens an auction and allows further bidding..
        /// </summary>
        public static string AuctionReopenHelp {
            get {
                return ResourceManager.GetString("AuctionReopenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen.
        /// </summary>
        public static string AuctionReopenLink {
            get {
                return ResourceManager.GetString("AuctionReopenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction Results by User.
        /// </summary>
        public static string AuctionResultsByUser {
            get {
                return ResourceManager.GetString("AuctionResultsByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string AuctionResumeLink {
            get {
                return ResourceManager.GetString("AuctionResumeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Auctions.
        /// </summary>
        public static string AuctionsAvailable {
            get {
                return ResourceManager.GetString("AuctionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Auctions.
        /// </summary>
        public static string AuctionsClosed {
            get {
                return ResourceManager.GetString("AuctionsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No auctions are running at this time..
        /// </summary>
        public static string AuctionsNoneRunning {
            get {
                return ResourceManager.GetString("AuctionsNoneRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Auction &quot;{0}&quot;.
        /// </summary>
        public static string AuctionStart {
            get {
                return ResourceManager.GetString("AuctionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string AuctionStartLink {
            get {
                return ResourceManager.GetString("AuctionStartLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string AuctionStatusClosed {
            get {
                return ResourceManager.GetString("AuctionStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string AuctionStatusDeleted {
            get {
                return ResourceManager.GetString("AuctionStatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string AuctionStatusPaused {
            get {
                return ResourceManager.GetString("AuctionStatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string AuctionStatusPending {
            get {
                return ResourceManager.GetString("AuctionStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string AuctionStatusRunning {
            get {
                return ResourceManager.GetString("AuctionStatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction: {0}.
        /// </summary>
        public static string AuctionTitle {
            get {
                return ResourceManager.GetString("AuctionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End automatically.
        /// </summary>
        public static string AutoEnd {
            get {
                return ResourceManager.GetString("AutoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic end time.
        /// </summary>
        public static string AutoEndTime {
            get {
                return ResourceManager.GetString("AutoEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start automatically.
        /// </summary>
        public static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic start time.
        /// </summary>
        public static string AutoStartTime {
            get {
                return ResourceManager.GetString("AutoStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Admin.
        /// </summary>
        public static string BackToAdmin {
            get {
                return ResourceManager.GetString("BackToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        public static string Behaviour {
            get {
                return ResourceManager.GetString("Behaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid for item.
        /// </summary>
        public static string BidForItem {
            get {
                return ResourceManager.GetString("BidForItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid too low.
        /// </summary>
        public static string BidTooLow {
            get {
                return ResourceManager.GetString("BidTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By user.
        /// </summary>
        public static string ByUser {
            get {
                return ResourceManager.GetString("ByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid.
        /// </summary>
        public static string CategoryBid {
            get {
                return ResourceManager.GetString("CategoryBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string CategoryGlobal {
            get {
                return ResourceManager.GetString("CategoryGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string CategoryRegistration {
            get {
                return ResourceManager.GetString("CategoryRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical.
        /// </summary>
        public static string CategoryTechnical {
            get {
                return ResourceManager.GetString("CategoryTechnical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANYNAME English.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All code is © {0} except for some standard NuGet packages, and the following items, which have been used under license..
        /// </summary>
        public static string CreditText {
            get {
                return ResourceManager.GetString("CreditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Images.
        /// </summary>
        public static string EditImages {
            get {
                return ResourceManager.GetString("EditImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Parameter.
        /// </summary>
        public static string EditParameter {
            get {
                return ResourceManager.GetString("EditParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File.
        /// </summary>
        public static string FileRemove {
            get {
                return ResourceManager.GetString("FileRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change font.
        /// </summary>
        public static string FontChange {
            get {
                return ResourceManager.GetString("FontChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Font.
        /// </summary>
        public static string FontDefault {
            get {
                return ResourceManager.GetString("FontDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts and colours.
        /// </summary>
        public static string FontsAndColours {
            get {
                return ResourceManager.GetString("FontsAndColours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string FontTitle {
            get {
                return ResourceManager.GetString("FontTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove image.
        /// </summary>
        public static string ImageRemove {
            get {
                return ResourceManager.GetString("ImageRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop images here.
        /// </summary>
        public static string ImagesDragAndDropHere {
            get {
                return ResourceManager.GetString("ImagesDragAndDropHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images for &quot;{0}&quot;.
        /// </summary>
        public static string ImagesFor {
            get {
                return ResourceManager.GetString("ImagesFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import more.
        /// </summary>
        public static string ImportMore {
            get {
                return ResourceManager.GetString("ImportMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leading bid.
        /// </summary>
        public static string LeadingBid {
            get {
                return ResourceManager.GetString("LeadingBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line no.
        /// </summary>
        public static string LineNo {
            get {
                return ResourceManager.GetString("LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        public static string Lot {
            get {
                return ResourceManager.GetString("Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot configuration.
        /// </summary>
        public static string LotConfiguration {
            get {
                return ResourceManager.GetString("LotConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Lot.
        /// </summary>
        public static string LotCreate {
            get {
                return ResourceManager.GetString("LotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LotDescription {
            get {
                return ResourceManager.GetString("LotDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Lot.
        /// </summary>
        public static string LotEdit {
            get {
                return ResourceManager.GetString("LotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Lot Images.
        /// </summary>
        public static string LotImagesEdit {
            get {
                return ResourceManager.GetString("LotImagesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first image will be used as the picture for the Lot. The other images can be seen by viewing the Lot Details..
        /// </summary>
        public static string LotImagesHelp {
            get {
                return ResourceManager.GetString("LotImagesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Lots.
        /// </summary>
        public static string LotImport {
            get {
                return ResourceManager.GetString("LotImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following data was imported:.
        /// </summary>
        public static string LotImportDataImported {
            get {
                return ResourceManager.GetString("LotImportDataImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Rows.
        /// </summary>
        public static string LotImportDataRows {
            get {
                return ResourceManager.GetString("LotImportDataRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop import files here.
        /// </summary>
        public static string LotImportDragAndDropHere {
            get {
                return ResourceManager.GetString("LotImportDragAndDropHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following good data was found but not imported.
        /// </summary>
        public static string LotImportGoodDataNotSaved {
            get {
                return ResourceManager.GetString("LotImportGoodDataNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Lots.
        /// </summary>
        public static string LotImportGoodLots {
            get {
                return ResourceManager.GetString("LotImportGoodLots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LotName {
            get {
                return ResourceManager.GetString("LotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        public static string LotReserve {
            get {
                return ResourceManager.GetString("LotReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Lots.
        /// </summary>
        public static string LotsAvailable {
            get {
                return ResourceManager.GetString("LotsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lots in Auction.
        /// </summary>
        public static string LotsInAuction {
            get {
                return ResourceManager.GetString("LotsInAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold.
        /// </summary>
        public static string LotSold {
            get {
                return ResourceManager.GetString("LotSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details....
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for a new account.
        /// </summary>
        public static string RegisterNewAccount {
            get {
                return ResourceManager.GetString("RegisterNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this browser?.
        /// </summary>
        public static string RememberThisBrowser {
            get {
                return ResourceManager.GetString("RememberThisBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        public static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (reserve not met).
        /// </summary>
        public static string ReserveNotMet {
            get {
                return ResourceManager.GetString("ReserveNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respect Reserves on lots.
        /// </summary>
        public static string ReserveUse {
            get {
                return ResourceManager.GetString("ReserveUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string RestartLink {
            get {
                return ResourceManager.GetString("RestartLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings and oprtions.
        /// </summary>
        public static string SettingsAndOptions {
            get {
                return ResourceManager.GetString("SettingsAndOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent Auction.
        /// </summary>
        public static string SilentAuction {
            get {
                return ResourceManager.GetString("SilentAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration.
        /// </summary>
        public static string SystemConfiguration {
            get {
                return ResourceManager.GetString("SystemConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make payment for {0}.
        /// </summary>
        public static string UserMakePayment {
            get {
                return ResourceManager.GetString("UserMakePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outstanding balance for {0}.
        /// </summary>
        public static string UserOutstanding {
            get {
                return ResourceManager.GetString("UserOutstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User overridable.
        /// </summary>
        public static string UserOverridable {
            get {
                return ResourceManager.GetString("UserOverridable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid by {0}.
        /// </summary>
        public static string UserPaid {
            get {
                return ResourceManager.GetString("UserPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total for {0}.
        /// </summary>
        public static string UserTotal {
            get {
                return ResourceManager.GetString("UserTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long.
        /// </summary>
        public static string ValidationErrorMinLength {
            get {
                return ResourceManager.GetString("ValidationErrorMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ValidationPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("ValidationPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! Log in to your account..
        /// </summary>
        public static string WelcomeLogIn {
            get {
                return ResourceManager.GetString("WelcomeLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        public static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning bid.
        /// </summary>
        public static string WinningBid {
            get {
                return ResourceManager.GetString("WinningBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your highest bid.
        /// </summary>
        public static string YourHighestBid {
            get {
                return ResourceManager.GetString("YourHighestBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your total leading bids.
        /// </summary>
        public static string YourTotalLeadingBids {
            get {
                return ResourceManager.GetString("YourTotalLeadingBids", resourceCulture);
            }
        }
    }
}
